module.exports = {
  NEXT_DAY: 'NEXT_DAY',
  PREVIOUS_DAY: 'PREVIOUS_DAY',
  PENDING_CALL: 'PENDING_CALL',
  LOADED: 'LOADED',
  ERROR: 'ERROR',
  PRIMETIME: 'PRIMETIME',
  SCROLL: 'SCROLL',
  WEEKLY: 'WEEKLY',
  PENDING_WEEKLY: 'PENDING_WEEKLY',
  WEEKLY_LOADED: 'WEEKLY_LOADED',
  WEEKLY_ERROR: 'WEEKLY_ERROR'
};
